### ISSUE TITLE
 RegistrationError: TransformerSpanClassificationTaskModule is not a registered name for TaskModule.

### ISSUE THREAD

**Issue by ArneBinder** [ArneBinder/pytorch-ie#416]
see https://github.com/ArneBinder/pytorch-ie-hydra-template-1/issues/162

**Comment by raphael10-collab** [comment]
I'm getting the same errors : 

    (.pytorch-ie) (base) raphy@raohy:~/pytorch-ie$ python3 ner_example.py 
    /home/raphy/pytorch-ie/.pytorch-ie/lib/python3.12/site-packages/huggingface_hub/file_download.py:795: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
      warnings.warn(
    taskmodule_config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 384/384 [00:00<00:00, 4.07MB/s]
    Traceback (most recent call last):
      File "/home/raphy/pytorch-ie/ner_example.py", line 19, in <module>
        ner_pipeline = AutoPipeline.from_pretrained("pie/example-ner-spanclf-conll03", device=-1, num_workers=0)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/raphy/pytorch-ie/.pytorch-ie/lib/python3.12/site-packages/pytorch_ie/auto.py", line 125, in from_pretrained
        taskmodule = AutoTaskModule.from_pretrained(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/raphy/pytorch-ie/.pytorch-ie/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
        return fn(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^
      File "/home/raphy/pytorch-ie/.pytorch-ie/lib/python3.12/site-packages/pytorch_ie/core/hf_hub_mixin.py", line 184, in from_pretrained
        return cls._from_pretrained(
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/raphy/pytorch-ie/.pytorch-ie/lib/python3.12/site-packages/pytorch_ie/auto.py", line 92, in _from_pretrained
        clazz: Type[TaskModule] = TaskModule.by_name(class_name)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/raphy/pytorch-ie/.pytorch-ie/lib/python3.12/site-packages/pytorch_ie/core/registrable.py", line 48, in by_name
        raise RegistrationError(f"{name} is not a registered name for {cls.__name__}.")
    pytorch_ie.core.registrable.RegistrationError: TransformerSpanClassificationTaskModule is not a registered name for TaskModule.


being ner_example.py  : https://github.com/ArneBinder/pytorch-ie?tab=readme-ov-file#span-classification-based-named-entity-recognition  : 
    
    (.pytorch-ie) (base) raphy@raohy:~/pytorch-ie$ cat ner_example.py 
    from dataclasses import dataclass
    
    from pytorch_ie.annotations import LabeledSpan
    from pytorch_ie.auto import AutoPipeline
    from pytorch_ie.core import AnnotationLayer, annotation_field
    from pytorch_ie.documents import TextDocument
    
    
    @dataclass
    class ExampleDocument(TextDocument):
        entities: AnnotationLayer[LabeledSpan] = annotation_field(target="text")
    
    
    document = ExampleDocument(
        "“Making a super tasty alt-chicken wing is only half of it,” said Po Bronson, general partner at SOSV and managing director of IndieBio."
    )
    
    # see below for the long version
    ner_pipeline = AutoPipeline.from_pretrained("pie/example-ner-spanclf-conll03", device=-1, num_workers=0)
    
    ner_pipeline(document)
    
    for entity in document.entities.predictions:
        print(f"{entity} -> {entity.label}")




and : 

    (.pytorch-ie) (base) raphy@raohy:~/pytorch-ie$ python relextract_example.py 
    /home/raphy/pytorch-ie/.pytorch-ie/lib/python3.12/site-packages/huggingface_hub/file_download.py:795: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
      warnings.warn(
    taskmodule_config.json: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2.56k/2.56k [00:00<00:00, 23.0MB/s]
    Traceback (most recent call last):
      File "/home/raphy/pytorch-ie/relextract_example.py", line 19, in <module>
        re_pipeline = AutoPipeline.from_pretrained("pie/example-re-textclf-tacred", device=-1, num_workers=0)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/raphy/pytorch-ie/.pytorch-ie/lib/python3.12/site-packages/pytorch_ie/auto.py", line 125, in from_pretrained
        taskmodule = AutoTaskModule.from_pretrained(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/raphy/pytorch-ie/.pytorch-ie/lib/python3.12/site-packages/huggingface_hub/utils/_validators.py", line 114, in _inner_fn
        return fn(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^
      File "/home/raphy/pytorch-ie/.pytorch-ie/lib/python3.12/site-packages/pytorch_ie/core/hf_hub_mixin.py", line 184, in from_pretrained
        return cls._from_pretrained(
               ^^^^^^^^^^^^^^^^^^^^^
      File "/home/raphy/pytorch-ie/.pytorch-ie/lib/python3.12/site-packages/pytorch_ie/auto.py", line 92, in _from_pretrained
        clazz: Type[TaskModule] = TaskModule.by_name(class_name)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/raphy/pytorch-ie/.pytorch-ie/lib/python3.12/site-packages/pytorch_ie/core/registrable.py", line 48, in by_name
        raise RegistrationError(f"{name} is not a registered name for {cls.__name__}.")
    pytorch_ie.core.registrable.RegistrationError: TransformerRETextClassificationTaskModule is not a registered name for TaskModule.


Being relextract_example.py  :  https://github.com/ArneBinder/pytorch-ie?tab=readme-ov-file#text-classification-based-relation-extraction


    (.pytorch-ie) (base) raphy@raohy:~/pytorch-ie$ cat relextract_example.py 
    from dataclasses import dataclass
    
    from pytorch_ie.annotations import BinaryRelation, LabeledSpan
    from pytorch_ie.auto import AutoPipeline
    from pytorch_ie.core import AnnotationLayer, annotation_field
    from pytorch_ie.documents import TextDocument
    
    
    @dataclass
    class ExampleDocument(TextDocument):
        entities: AnnotationLayer[LabeledSpan] = annotation_field(target="text")
        relations: AnnotationLayer[BinaryRelation] = annotation_field(target="entities")
    
    
    document = ExampleDocument(
        "“Making a super tasty alt-chicken wing is only half of it,” said Po Bronson, general partner at SOSV and managing director of IndieBio."
    )
    
    re_pipeline = AutoPipeline.from_pretrained("pie/example-re-textclf-tacred", device=-1, num_workers=0)
    
    for start, end, label in [(65, 75, "PER"), (96, 100, "ORG"), (126, 134, "ORG")]:
        document.entities.append(LabeledSpan(start=start, end=end, label=label))
    
    re_pipeline(document, batch_size=2)
    
    for relation in document.relations.predictions:
        print(f"({relation.head} -> {relation.tail}) -> {relation.label}")
    
    # Result:
    # (Po Bronson -> SOSV) -> per:employee_of
    # (Po Bronson -> IndieBio) -> per:employee_of
    # (SOSV -> Po Bronson) -> org:top_members/employees
    # (IndieBio -> Po Bronson) -> org:top_members/employees



How to make them work?

**Comment by ArneBinder** [comment]
Hi @raphael10-collab, did you see [this](https://github.com/ArneBinder/pytorch-ie-hydra-template-1/issues/162#issuecomment-2067646112)?

**Comment by raphael10-collab** [comment]
Thank you  @ArneBinder
